CREATE TABLE my_schema.continent_capital ( name  varchar(45) NOT NULL,  name_continent  varchar(15) NULL,  name_capital  varchar(15) NULL);

INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Andorra","Europe ","Andorra la Vella");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("United Arab Emirates","Asia ","Abu Dhabi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Afghanistan","Asia ","Kabul");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Antigua and Barbuda","North America ","St. John's");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Anguilla","North America ","The Valley");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Albania","Europe ","Tirana");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Armenia","Asia ","Yerevan");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Angola","Africa ","Luanda");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Antarctica","Antarctica ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Argentina","South America ","Buenos Aires");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("American Samoa","Oceania ","Pago Pago");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Austria","Europe ","Vienna");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Australia","Oceania ","Canberra");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Aruba","North America ","Oranjestad");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Åland Islands","Europe ","Mariehamn");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Azerbaijan","Asia ","Baku");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bosnia and Herzegovina","Europe ","Sarajevo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Barbados","North America ","Bridgetown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bangladesh","Asia ","Dhaka");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Belgium","Europe ","Brussels");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Burkina Faso","Africa ","Ouagadougou");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bulgaria","Europe ","Sofia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bahrain","Asia ","Manama");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Burundi","Africa ","Bujumbura");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Benin","Africa ","Porto-Novo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Barthélemy","North America ","Gustavia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bermuda","North America ","Hamilton");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Brunei Darussalam","Asia ","Bandar Seri Begawan");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bolivia","South America ","Sucre");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bonaire, Sint Eustatius and Saba","North America ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Brazil","South America ","Brasília");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bahamas","North America ","Nassau");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bhutan","Asia ","Thimphu");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Bouvet Island","Antarctica ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Botswana","Africa ","Gaborone");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Belarus","Europe ","Minsk");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Belize","North America ","Belmopan");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Canada","North America ","Ottawa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cocos [Keeling] Islands","Asia ","West Island");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Democratic Republic of the Congo","Africa ","Kinshasa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Central African Republic","Africa ","Bangui");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Republic of the Congo","Africa ","Brazzaville");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Switzerland","Europe ","Berne");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ivory Coast","Africa ","Yamoussoukro");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cook Islands","Oceania ","Avarua");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Chile","South America ","Santiago");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cameroon","Africa ","Yaoundé");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("China","Asia ","Beijing");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Colombia","South America ","Bogotá");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Costa Rica","North America ","San José");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cuba","North America ","Havana");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cape Verde","Africa ","Praia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Curaçao","North America ","Willemstad");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Christmas Island","Asia ","The Settlement");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cyprus","Europe ","Nicosia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Czech Republic","Europe ","Prague");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Germany","Europe ","Berlin");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Djibouti","Africa ","Djibouti");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Denmark","Europe ","Copenhagen");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Dominica","North America ","Roseau");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Dominican Republic","North America ","Santo Domingo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Algeria","Africa ","Algiers");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ecuador","South America ","Quito");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Estonia","Europe ","Tallinn");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Egypt","Africa ","Cairo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Western Sahara","Africa ","El Aaiún");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Eritrea","Africa ","Asmara");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Spain","Europe ","Madrid");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ethiopia","Africa ","Addis Ababa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Finland","Europe ","Helsinki");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Fiji","Oceania ","Suva");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Falkland Islands","South America ","Stanley");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Micronesia","Oceania ","Palikir");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Faroe Islands","Europe ","Tórshavn");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("France","Europe ","Paris");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Gabon","Africa ","Libreville");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("United Kingdom of Great Britain and Northern ","Europe ","London");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Grenada","North America ","St. George's");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Georgia","Asia ","Tbilisi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("French Guiana","South America ","Cayenne");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guernsey","Europe ","St Peter Port");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ghana","Africa ","Accra");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Gibraltar","Europe ","Gibraltar");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Greenland","North America ","Nuuk");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Gambia","Africa ","Banjul");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guinea","Africa ","Conakry");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guadeloupe","North America ","Basse-Terre");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Equatorial Guinea","Africa ","Malabo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Greece","Europe ","Athens");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("South Georgia and the South Sandwich Islands","Antarctica ","Grytviken");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guatemala","North America ","Guatemala City");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guam","Oceania ","Hagåtña");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guinea-Bissau","Africa ","Bissau");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Guyana","South America ","Georgetown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Hong Kong","Asia ","Hong Kong");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Heard Island and McDonald Islands","Antarctica ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Honduras","North America ","Tegucigalpa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Croatia","Europe ","Zagreb");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Haiti","North America ","Port-au-Prince");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Hungary","Europe ","Budapest");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Indonesia","Asia ","Jakarta");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ireland","Europe ","Dublin");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Israel","Asia ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Isle of Man","Europe ","Douglas");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("India","Asia ","New Delhi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("British Indian Ocean Territory","Asia ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Iraq","Asia ","Baghdad");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Iran","Asia ","Tehran");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Iceland","Europe ","Reykjavik");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Italy","Europe ","Rome");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Jersey","Europe ","Saint Helier");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Jamaica","North America ","Kingston");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Jordan","Asia ","Amman");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Japan","Asia ","Tokyo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kenya","Africa ","Nairobi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kyrgyzstan","Asia ","Bishkek");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cambodia","Asia ","Phnom Penh");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kiribati","Oceania ","Tarawa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Comoros","Africa ","Moroni");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Kitts and Nevis","North America ","Basseterre");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("North Korea","Asia ","Pyongyang");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("South Korea","Asia ","Seoul");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kuwait","Asia ","Kuwait City");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Cayman Islands","North America ","George Town");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kazakhstan","Asia ","Astana");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Laos","Asia ","Vientiane");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Lebanon","Asia ","Beirut");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Lucia","North America ","Castries");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Liechtenstein","Europe ","Vaduz");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Sri Lanka","Asia ","Colombo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Liberia","Africa ","Monrovia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Lesotho","Africa ","Maseru");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Lithuania","Europe ","Vilnius");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Luxembourg","Europe ","Luxembourg");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Latvia","Europe ","Riga");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Libya","Africa ","Tripoli");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Morocco","Africa ","Rabat");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Monaco","Europe ","Monaco");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Moldova","Europe ","Chişinău");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Montenegro","Europe ","Podgorica");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Martin","North America ","Marigot");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Madagascar","Africa ","Antananarivo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Marshall Islands","Oceania ","Majuro");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Macedonia","Europe ","Skopje");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mali","Africa ","Bamako");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Myanmar [Burma]","Asia ","Nay Pyi Taw");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mongolia","Asia ","Ulan Bator");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Macao","Asia ","Macao");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Northern Mariana Islands","Oceania ","Saipan");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Martinique","North America ","Fort-de-France");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mauritania","Africa ","Nouakchott");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Montserrat","North America ","Plymouth");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Malta","Europe ","Valletta");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mauritius","Africa ","Port Louis");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Maldives","Asia ","Malé");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Malawi","Africa ","Lilongwe");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mexico","North America ","Mexico City");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Malaysia","Asia ","Kuala Lumpur");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mozambique","Africa ","Maputo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Namibia","Africa ","Windhoek");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("New Caledonia","Oceania ","Noumea");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Niger","Africa ","Niamey");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Norfolk Island","Oceania ","Kingston");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Nigeria","Africa ","Abuja");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Nicaragua","North America ","Managua");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Netherlands","Europe ","Amsterdam");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Norway","Europe ","Oslo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Nepal","Asia ","Kathmandu");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Nauru","Oceania ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Niue","Oceania ","Alofi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("New Zealand","Oceania ","Wellington");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Oman","Asia ","Muscat");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Panama","North America ","Panama City");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Peru","South America ","Lima");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("French Polynesia","Oceania ","Papeete");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Papua New Guinea","Oceania ","Port Moresby");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Philippines","Asia ","Manila");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Pakistan","Asia ","Islamabad");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Poland","Europe ","Warsaw");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Pierre and Miquelon","North America ","Saint-Pierre");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Pitcairn Islands","Oceania ","Adamstown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Puerto Rico","North America ","San Juan");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Palestine","Asia ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Portugal","Europe ","Lisbon");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Palau","Oceania ","Melekeok - Palau State Capital");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Paraguay","South America ","Asunción");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Qatar","Asia ","Doha");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Réunion","Africa ","Saint-Denis");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Romania","Europe ","Bucharest");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Serbia","Europe ","Belgrade");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Russia","Europe ","Moscow");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Rwanda","Africa ","Kigali");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saudi Arabia","Asia ","Riyadh");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Solomon Islands","Oceania ","Honiara");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Seychelles","Africa ","Victoria");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Sudan","Africa ","Khartoum");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Sweden","Europe ","Stockholm");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Singapore","Asia ","Singapore");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Helena","Africa ","Jamestown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Slovenia","Europe ","Ljubljana");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Svalbard and Jan Mayen","Europe ","Longyearbyen");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Slovakia","Europe ","Bratislava");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Sierra Leone","Africa ","Freetown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("San Marino","Europe ","San Marino");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Senegal","Africa ","Dakar");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Somalia","Africa ","Mogadishu");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Suriname","South America ","Paramaribo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("South Sudan","Africa ","Juba");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("São Tomé and Príncipe","Africa ","São Tomé");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("El Salvador","North America ","San Salvador");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Sint Maarten","North America ","Philipsburg");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Syria","Asia ","Damascus");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Swaziland","Africa ","Mbabane");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Turks and Caicos Islands","North America ","Cockburn Town");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Chad","Africa ","N'Djamena");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("French Southern Territories","Antarctica ","Port-aux-Français");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Togo","Africa ","Lomé");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Thailand","Asia ","Bangkok");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tajikistan","Asia ","Dushanbe");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tokelau","Oceania ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("East Timor","Oceania ","Dili");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Turkmenistan","Asia ","Ashgabat");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tunisia","Africa ","Tunis");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tonga","Oceania ","Nuku'alofa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Turkey","Asia ","Ankara");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Trinidad and Tobago","North America ","Port of Spain");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tuvalu","Oceania ","Funafuti");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Taiwan","Asia ","Taipei");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Tanzania","Africa ","Dodoma");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Ukraine","Europe ","Kyiv");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Uganda","Africa ","Kampala");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("U.S. Minor Outlying Islands","Oceania ","");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("United States","North America ","Washington");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Uruguay","South America ","Montevideo");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Uzbekistan","Asia ","Tashkent");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Vatican City","Europe ","Vatican");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Saint Vincent and the Grenadines","North America ","Kingstown");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Venezuela","South America ","Caracas");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("British Virgin Islands","North America ","Road Town");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("U.S. Virgin Islands","North America ","Charlotte Amalie");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Vietnam","Asia ","Hanoi");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Vanuatu","Oceania ","Port Vila");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Wallis and Futuna","Oceania ","Mata-Utu");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Samoa","Oceania ","Apia");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Kosovo","Europe ","Pristina");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Yemen","Asia ","Sanaa");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Mayotte","Africa ","Mamoutzou");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("South Africa","Africa ","Pretoria");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Zambia","Africa ","Lusaka");
INSERT INTO  my_schema.continent_capital ( name , name_continent , name_capital ) VALUES ("Zimbabwe","Africa ","Harare");
